require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable

  Exclude:
    - db/**/*
    - script/**/*
    - bin/**/*
    - config/**/*

Layout/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
