require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable

  Exclude:
    - db/**/*
    - script/**/*
    - bin/**/*
    - config/**/*

Layout/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*

Metrics/MethodLength:
  Max: 30

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Style/BlockDelimiters:
  EnforcedStyle: semantic
  AllowBracesOnProceduralOneLiners: true

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: true

RSpec/MultipleExpectations:
  Max: 5

RSpec/ExampleLength:
  Max: 25
