---

services:
  db:
    container_name: zantop_db
    image: "postgres:13.4-alpine"
    environment:
      - POSTGRES_USER=zantop
      - POSTGRES_PASSWORD=zantop
    volumes:
      - database_files:/var/lib/postgresql/data
    ports:
      - "5445:5432"

networks:
  default:
    name: zantop_default

volumes:
  database_files:
