default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("ZANTOP_DATABASE_HOST") { "localhost" } %>
  username: <%= ENV["ZANTOP_DATABASE_USER"] %>
  password: <%= ENV["ZANTOP_DATABASE_PASSWORD"] %>
  port: <%= ENV.fetch("ZANTOP_DATABASE_PORT") { 5432 } %>

development: &development
  <<: *default
  database: zantop_development
  username: <%= ENV.fetch("ZANTOP_DATABASE_USER") { "zantop" } %>
  password: <%= ENV.fetch("ZANTOP_DATABASE_PASSWORD") { "zantop" } %>
  port: <%= ENV.fetch("ZANTOP_DATABASE_PORT") { 5445 } %>

test:
  <<: *development
  database: zantop_test

production:
  <<: *default
  database: zantop_production
  username: <%= Rails.application.credentials.dig(:db, :username) %>
  password: <%= Rails.application.credentials.dig(:db, :password) %>
