default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("ZANTOP_DATABASE_HOST") { "localhost" } %>
  username: <%= ENV["ZANTOP_DATABASE_USER"] %>
  password: <%= ENV["ZANTOP_DATABASE_PASSWORD"] %>
  port: <%= ENV.fetch("ZANTOP_DATABASE_PORT") { 5432 } %>

development:
  <<: *default
  database: zantop_development

test:
  <<: *default
  database: zantop_test

production:
  <<: *default
  database: zantop_production
