default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("ZANTOP_DATABASE_HOST") { "localhost" } %>
  username: <%= ENV["ZANTOP_DATABASE_USER"] %>
  password: <%= ENV["ZANTOP_DATABASE_PASSWORD"] %>

development:
  <<: *default
  database: zantop_development

test:
  <<: *default
  database: zantop_test

production:
  <<: *default
  database: zantop_production
