name: Rubocop

on: [push]

env:
  RUBY_VERSION: 3.0.2

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: actions/setup-ruby@v1

    - name: Set up gems cache
      uses: actions/cache@preview
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-rubocop-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-rubocop-

    - name: Install Ruby dependencies
      run: |
        gem install bundler
        bundle install

    - name: Run rubocop
      run: bundle exec rubocop --parallel
