name: Rubocop

on: [pull_request]

env:
  RUBY_VERSION: 3.0.2

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ env.RUBY_VERSION }}
        bundler-cache: true

    - name: Install Ruby dependencies
      run: |
        gem install bundler
        bundle install

    - name: Get changed files using defaults
      id: changed-files
      uses: jitterbit/get-changed-files@v1

    - name: Run rubocop for changed or added files
      run: bundle exec rubocop ${{ steps.changed-files.outputs.added_modified }}
